name: cinema_app
description: A new Flutter project for cinema website.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/